import Mathlib

/-!
# Finite frame/projector kernel

A rectangular frame `Q` together with an explicit left inverse `A` defines
`P = Q A`.  The sole hypothesis `A Q = I` already forces `P` to be idempotent.
This is the finite algebra needed before any geometric, SU(3), or continuum
interpretation.  No adjoint, smoothness, bundle, or spacetime hypothesis is
hidden here.
-/

open Matrix

namespace YangMillsFinite

variable {K : Type*} [CommRing K]
variable {a r : Type*} [Fintype a] [Fintype r] [DecidableEq a] [DecidableEq r]

/-- Projector generated by a frame `Q` and a chosen left inverse `A`. -/
def frameProjector (Q : Matrix a r K) (A : Matrix r a K) : Matrix a a K :=
  Q * A

/-- A left-invertible frame produces an idempotent projector. -/
theorem frameProjector_idempotent
    (Q : Matrix a r K) (A : Matrix r a K)
    (hAQ : A * Q = 1) :
    frameProjector Q A * frameProjector Q A = frameProjector Q A := by
  simpa [frameProjector, Matrix.mul_assoc] using
    congrArg (fun X : Matrix r r K => Q * X * A) hAQ

/-- The frame lies in the image of its generated projector. -/
theorem frameProjector_fixes_frame
    (Q : Matrix a r K) (A : Matrix r a K)
    (hAQ : A * Q = 1) :
    frameProjector Q A * Q = Q := by
  simpa [frameProjector, Matrix.mul_assoc] using
    congrArg (fun X : Matrix r r K => Q * X) hAQ

/-- The complementary idempotent annihilates the frame. -/
theorem complement_annihilates_frame
    (Q : Matrix a r K) (A : Matrix r a K)
    (hAQ : A * Q = 1) :
    (1 - frameProjector Q A) * Q = 0 := by
  calc
    (1 - frameProjector Q A) * Q = Q - frameProjector Q A * Q := by
      rw [Matrix.sub_mul, Matrix.one_mul]
    _ = Q - Q := by rw [frameProjector_fixes_frame Q A hAQ]
    _ = 0 := sub_self Q

end YangMillsFinite

#print axioms YangMillsFinite.frameProjector_idempotent
#print axioms YangMillsFinite.frameProjector_fixes_frame
#print axioms YangMillsFinite.complement_annihilates_frame
