/-
The finite moving-frame identity behind the common-clock theorem (programme item T4 and
§9.3 / Theorem P4 of "The Dirac Time of the Gigantefermion", Jeromie Beasley,
DOI 10.5281/zenodo.22978631).

Write the state in a unitary frame, `ψ = R χ`. If `iħ ψ̇ = H ψ` and `ψ̇ = Ṙ χ + R χ̇`
(product rule), then the frame state obeys

  iħ χ̇ = (R† H R − iħ R† Ṙ) χ.

So the dynamics seen in the frame are generated by `R† H R − iħ R† Ṙ`, not by `R† H R`:
matching instantaneous spectra is not enough, the frame connection `−iħ R† Ṙ` matters.
When that generator equals `τ̇ H₀ + a I`, the frame state advances by the fixed generator
`H₀` at rate `τ̇`, up to a scalar phase.

The identity is proved at each instant from the product rule; existence and uniqueness of
solutions and the propagator form of Theorem P4 are not formalized here.
-/
import Mathlib

namespace DiracTime.MovingFrame

open Matrix

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- **Moving-frame identity.** -/
theorem moving_frame_identity (ħ : ℝ) (R R' H : Matrix n n ℂ) (χ χ' ψ' : n → ℂ)
    (hU : star R * R = 1) (hprod : ψ' = R' *ᵥ χ + R *ᵥ χ')
    (hS : (Complex.I * ħ) • ψ' = H *ᵥ (R *ᵥ χ)) :
    (Complex.I * ħ) • χ' = (star R * H * R - (Complex.I * ħ) • (star R * R')) *ᵥ χ := by
  have h1 : star R *ᵥ ψ' = (star R * R') *ᵥ χ + χ' := by
    rw [hprod, mulVec_add, mulVec_mulVec, mulVec_mulVec, hU, one_mulVec]
  have h2 : (Complex.I * ħ) • (star R *ᵥ ψ') = (star R * H * R) *ᵥ χ := by
    rw [← mulVec_smul, hS, mulVec_mulVec, mulVec_mulVec]
  rw [sub_mulVec, smul_mulVec, ← h2, h1, smul_add]
  abel

/-- **Common-clock form.** If the frame generator is `τ̇ H₀ + a I`, the frame state is
driven by the fixed generator `H₀` at rate `τ̇`, plus a scalar phase. -/
theorem common_clock (ħ τdot a : ℝ) (R R' H H₀ : Matrix n n ℂ) (χ χ' ψ' : n → ℂ)
    (hU : star R * R = 1) (hprod : ψ' = R' *ᵥ χ + R *ᵥ χ')
    (hS : (Complex.I * ħ) • ψ' = H *ᵥ (R *ᵥ χ))
    (hgen : star R * H * R - (Complex.I * ħ) • (star R * R') =
      (τdot : ℂ) • H₀ + (a : ℂ) • (1 : Matrix n n ℂ)) :
    (Complex.I * ħ) • χ' = (τdot : ℂ) • (H₀ *ᵥ χ) + (a : ℂ) • χ := by
  rw [moving_frame_identity ħ R R' H χ χ' ψ' hU hprod hS, hgen, add_mulVec,
    smul_mulVec, smul_mulVec, one_mulVec]

end DiracTime.MovingFrame
